config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :settings
  end

  get 'videos/index'

  get 'contact/index'

  get 'reviews/index'

  get 'errors/not_found'

  get "/404", to: "errors#not_found"

  resources :feedbacks, only: :create 
  
  resources :price, except: [:new, :update, :create, :show] do
    collection do
      get "theapeutic", as: :theapeutic 
      get "cosmetic", as: :cosmetic
    end
  end

  namespace :admin do
    resources :therapeutic_services do
      post 'reorder', on: :collection
    end
    resources :cosmetic_services do
      post 'reorder', on: :collection
    end
    resources :events
    resources :experts do
      post 'reorder', on: :collection
    end
    resources :questions
    resources :feedbacks
    resources :service_prices do
      post 'reorder', on: :collection
    end
    resources :sliders do
      post 'reorder', on: :collection
    end
    
    resources :photos do
      post 'reorder', on: :collection
    end
    resources :prices do
      post 'reorder', on: :collection
    end
    resources :videos do
      post 'reorder', on: :collection
    end
    resources :reviews
    get 'services/index'
    
  end

  resources :events do
    get ':marker' => "events#marked", as: :marked, on: :collection
  end

  resources :experts 
  
  resources :questions do
    get ':tag' => "questions#tagged", as: :tagged, on: :collection
  end

  resources :reviews do
    collection do
      get 'videos'
      get 'written'
      get ':tag' => "reviews#tagged", as: :tagged
    end
  end

  root 'pages#index'
  get 'pages/show'

  # get 'service/show/:id'
  resources :services do
    get "category/:category_id/" => "services#category", as: :category, on: :collection
    # get "type/:type" => "services#index"
    get ":type" => "services#type", as: :type, on: :collection
    get ":type" => "services#show", as: :show, on: :member
  end
  
  comfy_route :cms_admin, :path => '/admin'

  get '/search', to: 'search#index', as: :search
  
  get '/about*cms_page' => "pages#about", :constraints => { :format => 'html' }
  get '/about' => "pages#about"

  get '/specialists*cms_page' => "pages#specialists"
  get '/specialists' => "pages#specialists"
end

app/models/event.rb
class Event < ActiveRecord::Base
  MARKERS = ["news", "article", "promo"].freeze

  has_attached_file :image, :styles => { :medium => "300x300#", :thumb => "80x80>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  validates_presence_of :date, :title, :content

  # -- Relationships --------------------------------------------------------


  # -- Callbacks ------------------------------------------------------------


  # -- Validations ----------------------------------------------------------


  # -- Scopes ---------------------------------------------------------------


  # -- Class Methods --------------------------------------------------------


  # -- Instance Methods -----------------------------------------------------
  def full_path
    "/events/#{id}"
  end
  
  def label
    title
  end

  def content_cache
    content
  end

end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Comfy::Admin::Cms::BaseController

  before_action :build_event,  :only => [:new, :create]
  before_action :load_event,   :only => [:show, :edit, :update, :destroy]

  def index
    @events = Event.page(params[:page])
  end

  def show
    render
  end

  def new
    render
  end

  def edit
    render
  end

  def create
    @event.save!
    flash[:success] = 'Событие добавлено'
    redirect_to :action => :index
  rescue ActiveRecord::RecordInvalid
    flash.now[:danger] = 'Ошибка'
    render :action => :new
  end

  def update
    @event.update_attributes!(event_params)
    flash[:success] = 'Обновлено'
    redirect_to :action => :index
  rescue ActiveRecord::RecordInvalid
    flash.now[:danger] = 'Ошибка'
    render :action => :edit
  end

  def destroy
    @event.destroy
    flash[:success] = 'Удалено'
    redirect_to :action => :index
  end

protected

  def build_event
    @event = Event.new(event_params)
  end

  def load_event
    @event = Event.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:danger] = 'не найдено'
    redirect_to :action => :index
  end

  def event_params
    params.fetch(:event, {}).permit(:date, :title, :content, :marker, :image)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all.page(params[:page])
  end

  def show
    @event = Event.find(params[:id])
  end

  def marked
    @events = Event.where(marker: params[:marker]).page(params[:page])
    render "index"
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/_form.html.slim
= form.text_field :date, label: "Дата", style: "width: 150px", class: "datepicker"
= form.text_field :title, label: "Заголовок"
= form.text_area :content, class: "wysiwyg"

div.form-group style="margin: 0 160px" 
  - Event::MARKERS.each do |marker|
    = form.radio_button "marker", marker, label: t(marker)

div.form-group style="margin: 0 160px"
  = image_tag @event.image.url(:thumb) if @event.image.exists?

= form.file_field :image, label: "Изображение"

= form.form_group :class => 'form-actions' do
  = form.submit "Сохранить", :class => 'btn btn-primary'

app/views/admin/events/edit.html.haml
.page-header
  %h2 Изменить событие

= comfy_form_for [:admin, @event] do |form|
  = render form

app/views/admin/events/index.html.haml
.page-header
  = link_to 'Новое событие', new_admin_event_path, :class => 'btn btn-default pull-right'
  %h2= 'События'

= paginate @events, :theme => 'comfy'

%table.table.table-hover.table-bordered
  %tr
    %th Дата
    %th Заголовок
    %th.main Содержание
    %th Маркер
    %th Картинка
    %th
  - @events.each do |event|
    %tr
      %td= event.date.to_date
      %td= event.title
      %td.main= event.content
      %td= event.marker
      %td= image_tag event.image.url(:thumb) if event.image.exists?
      %td
        .btn-group.btn-group-sm
          = link_to 'Изменить', edit_admin_event_path(event), :class => 'btn btn-default'
          = link_to 'Удалить', admin_event_path(event), :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-danger'

= paginate @events, :theme => 'comfy'

app/views/admin/events/new.html.haml
.page-header
  %h2 Новое Событие

= comfy_form_for [:admin, @event] do |form|
  = render form

app/views/admin/events/show.html.haml
.page-header
  %h2 Event
  
= debug @event