config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :settings
  end

  get 'videos/index'

  get 'contact/index'

  get 'reviews/index'

  get 'errors/not_found'

  get "/404", to: "errors#not_found"

  resources :feedbacks, only: :create 
  
  resources :price, except: [:new, :update, :create, :show] do
    collection do
      get "theapeutic", as: :theapeutic 
      get "cosmetic", as: :cosmetic
    end
  end

  namespace :admin do
    resources :therapeutic_services do
      post 'reorder', on: :collection
    end
    resources :cosmetic_services do
      post 'reorder', on: :collection
    end
    resources :events
    resources :experts do
      post 'reorder', on: :collection
    end
    resources :questions
    resources :feedbacks
    resources :service_prices do
      post 'reorder', on: :collection
    end
    resources :sliders do
      post 'reorder', on: :collection
    end
    
    resources :photos do
      post 'reorder', on: :collection
    end
    resources :prices do
      post 'reorder', on: :collection
    end
    resources :videos do
      post 'reorder', on: :collection
    end
    resources :reviews
    get 'services/index'
    
  end

  resources :events do
    get ':marker' => "events#marked", as: :marked, on: :collection
  end

  resources :experts 
  
  resources :questions do
    get ':tag' => "questions#tagged", as: :tagged, on: :collection
  end

  resources :reviews do
    collection do
      get 'videos'
      get 'written'
      get ':tag' => "reviews#tagged", as: :tagged
    end
  end

  root 'pages#index'
  get 'pages/show'

  # get 'service/show/:id'
  resources :services do
    get "category/:category_id/" => "services#category", as: :category, on: :collection
    # get "type/:type" => "services#index"
    get ":type" => "services#type", as: :type, on: :collection
    get ":type" => "services#show", as: :show, on: :member
  end
  
  comfy_route :cms_admin, :path => '/admin'

  get '/search', to: 'search#index', as: :search
  
  get '/about*cms_page' => "pages#about", :constraints => { :format => 'html' }
  get '/about' => "pages#about"

  get '/specialists*cms_page' => "pages#specialists"
  get '/specialists' => "pages#specialists"
end

app/models/photo.rb
class Photo < ActiveRecord::Base

  has_attached_file :image, :styles => {:medium => "300x260#", :thumb => "100x104>" }, :default_url => "/assets/:style/missing_doctor.jpg"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  validates_presence_of :title, :image
  # -- Relationships --------------------------------------------------------


  # -- Callbacks ------------------------------------------------------------


  # -- Validations ----------------------------------------------------------


  # -- Scopes ---------------------------------------------------------------
  default_scope -> {order('position')}


  # -- Class Methods --------------------------------------------------------


  # -- Instance Methods -----------------------------------------------------


end

app/controllers/admin/photos_controller.rb
class Admin::PhotosController < Comfy::Admin::Cms::BaseController

  before_action :build_photo,  :only => [:new, :create]
  before_action :load_photo,   :only => [:show, :edit, :update, :destroy]

  def index
    @photos = Photo.order("position").page(params[:page])
  end

  def reorder
    params[:photo].each_with_index do |id, position|
      Photo.find(id).update_attribute(:position, position)
    end
    render nothing: true
  end
  
  def show
    render
  end

  def new
    render
  end

  def edit
    render
  end

  def create
    @photo.save!
    flash[:success] = 'Создано'
    redirect_to :action => :index
  rescue ActiveRecord::RecordInvalid
    flash.now[:danger] = 'Ошибка'
    render :action => :new
  end

  def update
    @photo.update_attributes!(photo_params)
    flash[:success] = 'Обновлено'
    redirect_to :action => :index
  rescue ActiveRecord::RecordInvalid
    flash.now[:danger] = 'Ошибка'
    render :action => :edit
  end

  def destroy
    @photo.destroy
    flash[:success] = 'Удалено'
    redirect_to :action => :index
  end

protected

  def build_photo
    @photo = Photo.new(photo_params)
  end

  def load_photo
    @photo = Photo.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:danger] = 'не найдено'
    redirect_to :action => :index
  end

  def photo_params
    params.fetch(:photo, {}).permit(:title, :image)
  end
end

app/views/admin/photos/_form.html.slim
= form.text_field :title, label: "Заголовок"
= form.file_field :image, label: "Изображение"

div.form-group style="margin: 0 160px"
  = image_tag @photo.image.url(:thumb) if @photo.image.exists?

= form.form_group :class => 'form-actions' do
  = form.submit "Сохранить", :class => 'btn btn-primary'

app/views/admin/photos/edit.html.haml
.page-header
  %h2 Изменить

= comfy_form_for [:admin, @photo] do |form|
  = render form

app/views/admin/photos/index.html.haml
.page-header
  = link_to 'Новую картинку', new_admin_photo_path, :class => 'btn btn-default pull-right'
  %h2= 'ФотоГалерея'

= paginate @photos, :theme => 'comfy'

%table.table.table-hover.table-bordered
  %thead
    %tr
      %th Изображение
      %th.main Заголовок
      %th
  %tbody.sortable_table
    - @photos.each do |photo|
      %tr{id: dom_id(photo)}
        %td= image_tag photo.image.url(:thumb)
        %td.main= photo.title
        %td
          .btn-group.btn-group-sm
            = link_to 'Изменить', edit_admin_photo_path(photo), :class => 'btn btn-default'
            = link_to 'Удалить', admin_photo_path(photo), :method => :delete, :data => { :confirm => 'Вы уверены?' }, :class => 'btn btn-danger'

= paginate @photos, :theme => 'comfy'

app/views/admin/photos/new.html.haml
.page-header
  %h2 Новое фото

= comfy_form_for [:admin, @photo] do |form|
  = render form

app/views/admin/photos/show.html.haml
.page-header
  %h2 Photo
  
= debug @photo