config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :settings
  end

  get 'videos/index'

  get 'contact/index'

  get 'reviews/index'

  get 'errors/not_found'

  get "/404", to: "errors#not_found"

  resources :feedbacks, only: :create 
  
  resources :price, except: [:new, :update, :create, :show] do
    collection do
      get "theapeutic", as: :theapeutic 
      get "cosmetic", as: :cosmetic
    end
  end

  namespace :admin do
    resources :therapeutic_services do
      post 'reorder', on: :collection
    end
    resources :cosmetic_services do
      post 'reorder', on: :collection
    end
    resources :events
    resources :experts do
      post 'reorder', on: :collection
    end
    resources :questions
    resources :feedbacks
    resources :service_prices do
      post 'reorder', on: :collection
    end
    resources :sliders do
      post 'reorder', on: :collection
    end
    
    resources :photos do
      post 'reorder', on: :collection
    end
    resources :prices do
      post 'reorder', on: :collection
    end
    resources :videos do
      post 'reorder', on: :collection
    end
    resources :reviews
    get 'services/index'
    
  end

  resources :events do
    get ':marker' => "events#marked", as: :marked, on: :collection
  end

  resources :experts 
  
  resources :questions do
    get ':tag' => "questions#tagged", as: :tagged, on: :collection
  end

  resources :reviews do
    collection do
      get 'videos'
      get 'written'
      get ':tag' => "reviews#tagged", as: :tagged
    end
  end

  root 'pages#index'
  get 'pages/show'

  # get 'service/show/:id'
  resources :services do
    get "category/:category_id/" => "services#category", as: :category, on: :collection
    # get "type/:type" => "services#index"
    get ":type" => "services#type", as: :type, on: :collection
    get ":type" => "services#show", as: :show, on: :member
  end
  
  comfy_route :cms_admin, :path => '/admin'

  get '/search', to: 'search#index', as: :search
  
  get '/about*cms_page' => "pages#about", :constraints => { :format => 'html' }
  get '/about' => "pages#about"

  get '/specialists*cms_page' => "pages#specialists"
  get '/specialists' => "pages#specialists"
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < Comfy::Admin::Cms::BaseController

  before_action :build_review,  :only => [:new, :create]
  before_action :load_review,   :only => [:show, :edit, :update, :destroy]
  before_action :load_tags
  def index
    @reviews = Review.page(params[:page])
  end

  def show
    render
  end

  def new
    render
  end

  def edit
    render
  end

  def create
    @review.save!
    flash[:success] = 'Отзыв добавлен'
    redirect_to :action => :index
  rescue ActiveRecord::RecordInvalid
    flash.now[:danger] = 'Ошибка'
    render :action => :new
  end

  def update
    @review.update_attributes!(review_params)
    flash[:success] = 'Обновлено'
    redirect_to :action => :index
  rescue ActiveRecord::RecordInvalid
    flash.now[:danger] = 'Ошибка при обновлении'
    render :action => :edit
  end

  def destroy
    @review.destroy
    flash[:success] = 'Удалено'
    redirect_to :action => :index
  end

protected

  def build_review
    @review = Review.new(review_params)
  end

  def load_review
    @review = Review.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:danger] = 'не найдено'
    redirect_to :action => :index
  end

  def load_tags
    @tags = Review.tag_counts_on(:tags)
  end

  def review_params
    params.fetch(:review, {}).permit(:name, :email, :content, :kind, :url, :published, :tag_list)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :load_all_tags
  def index
    @written = Review.written.published
    @videos = Review.videos.published
    @review = Review.new
  end

  def create
    review = Review.create(review_params)
    redirect_to reviews_path
    FeedbacksMailer.send_question(review, subj: "Отзыв").deliver
  end

  def tagged
    reviews = Review.tagged_with(params[:tag])
    
    @written = reviews.written.published
    @videos = reviews.videos.published
    @review = Review.new
    render :index
  end

  def videos
    @videos = Review.videos.published
    @review = Review.new
    render :index
  end

  def written
    @written = Review.written.published
    @review = Review.new
    render :index
  end

  private
  def review_params
    params.require(:review).permit(:name, :email, :content, :tags)
  end

  def load_all_tags
    @all_tags = Review.tag_counts_on(:tags)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/admin/reviews/_form.html.slim
= form.text_field :name, label: "Имя"
= form.text_field :email
= form.text_area :content, label: "Текст"

div.form-group style="margin: 0 160px" 
  - Review::KINDS.each do |kind|
    = form.radio_button "kind", kind, label: t(kind)

= form.text_field :url, label: "Ссылка из YouTube"

div.form-group style="margin: 0 160px"
  = form.check_box :published, label: "Опубликовать"

= form.text_field :tag_list, label: "Тэги", class: "tagList"

= form.form_group :class => 'form-actions' do
  = form.submit "Создать", :class => 'btn btn-primary'

javascript:
  $('.tagList').tagsinput();

  $('.tagList').typeahead({
    source: #{raw @tags.map(&:name)}
  });

app/views/admin/reviews/edit.html.haml
.page-header
  %h2 Изменить

= comfy_form_for [:admin, @review] do |form|
  = render form

app/views/admin/reviews/index.html.haml
.page-header
  = link_to 'Новый отзыв', new_admin_review_path, :class => 'btn btn-default pull-right'
  %h2= 'Отзывы'

= paginate @reviews, :theme => 'comfy'

%table.table.table-hover.table-bordered
  %tr
    %th Имя
    %th Email
    %th.main Отзыв
    %th Тип
    %th Опубликовано
    %th Тэги
    %th
  - @reviews.each do |review|
    %tr
      %td= review.name
      %td= review.email
      %td.main= truncate review.content
      %td= t(review.kind)
      %td= review.published? ? "да" : "нет"
      %td= review.tags.map(&:name).join(' ')
      %td
        .btn-group.btn-group-sm
          = link_to 'Изменить', edit_admin_review_path(review), :class => 'btn btn-default'
          = link_to 'Удалить', admin_review_path(review), :method => :delete, :data => { :confirm => 'Вы уверены?' }, :class => 'btn btn-danger'

= paginate @reviews, :theme => 'comfy'

app/views/admin/reviews/new.html.haml
.page-header
  %h2 Новый отзыв

= comfy_form_for [:admin, @review] do |form|
  = render form

app/views/admin/reviews/show.html.haml
.page-header
  %h2 Review
  
= debug @review