config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :settings
  end

  get 'videos/index'

  get 'contact/index'

  get 'reviews/index'

  get 'errors/not_found'

  get "/404", to: "errors#not_found"

  resources :feedbacks, only: :create 
  
  resources :price, except: [:new, :update, :create, :show] do
    collection do
      get "theapeutic", as: :theapeutic 
      get "cosmetic", as: :cosmetic
    end
  end

  namespace :admin do
    resources :therapeutic_services do
      post 'reorder', on: :collection
    end
    resources :cosmetic_services do
      post 'reorder', on: :collection
    end
    resources :events
    resources :experts do
      post 'reorder', on: :collection
    end
    resources :questions
    resources :feedbacks
    resources :service_prices do
      post 'reorder', on: :collection
    end
    resources :sliders do
      post 'reorder', on: :collection
    end
    
    resources :photos do
      post 'reorder', on: :collection
    end
    resources :prices do
      post 'reorder', on: :collection
    end
    resources :videos do
      post 'reorder', on: :collection
    end
    resources :reviews
    get 'services/index'
    
  end

  resources :events do
    get ':marker' => "events#marked", as: :marked, on: :collection
  end

  resources :experts 
  
  resources :questions do
    get ':tag' => "questions#tagged", as: :tagged, on: :collection
  end

  resources :reviews do
    collection do
      get 'videos'
      get 'written'
      get ':tag' => "reviews#tagged", as: :tagged
    end
  end

  root 'pages#index'
  get 'pages/show'

  # get 'service/show/:id'
  resources :services do
    get "category/:category_id/" => "services#category", as: :category, on: :collection
    # get "type/:type" => "services#index"
    get ":type" => "services#type", as: :type, on: :collection
    get ":type" => "services#show", as: :show, on: :member
  end
  
  comfy_route :cms_admin, :path => '/admin'

  get '/search', to: 'search#index', as: :search
  
  get '/about*cms_page' => "pages#about", :constraints => { :format => 'html' }
  get '/about' => "pages#about"

  get '/specialists*cms_page' => "pages#specialists"
  get '/specialists' => "pages#specialists"
end

app/models/expert.rb
class Expert < ActiveRecord::Base
  include MetaTags
  GENDERS = ["m", "f"].freeze

  has_attached_file :avatar, :styles => {:lg => "380x505#", :medium => "220x300#", :thumb => "100x100#" }, :default_url => "/assets/:style/missing_doctor.jpg"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  validates_presence_of :name

  # -- Relationships --------------------------------------------------------


  # -- Callbacks ------------------------------------------------------------


  # -- Validations ----------------------------------------------------------


  # -- Scopes ---------------------------------------------------------------
  default_scope -> {order('position')}


  # -- Class Methods --------------------------------------------------------


  # -- Instance Methods -----------------------------------------------------
  def full_path
    "/experts/#{id}"
  end

  def label
    name
  end

  def content_cache
    description
  end
end

app/controllers/admin/experts_controller.rb
class Admin::ExpertsController < Comfy::Admin::Cms::BaseController

  before_action :build_expert,  :only => [:new, :create]
  before_action :load_expert,   :only => [:show, :edit, :update, :destroy]
  before_action :build_meta_tag, only: [:new, :edit]
  def index
    @experts = Expert.order("position").page(params[:page])
  end
  
  def reorder
    params[:expert].each_with_index do |id, position|
      Expert.find(id).update_attribute(:position, position)
    end
    render nothing: true
  end

  def show
    render
  end

  def new
    render
  end

  def edit
    render
  end

  def create
    @expert.save!
    flash[:success] = 'Создан'
    redirect_to :action => :index
  rescue ActiveRecord::RecordInvalid
    flash.now[:danger] = 'Ошибка'
    render :action => :new
  end

  def update
    @expert.update_attributes!(expert_params)
    flash[:success] = 'Обновлено'
    redirect_to :action => :index
  rescue ActiveRecord::RecordInvalid
    flash.now[:danger] = 'Ошибка'
    render :action => :edit
  end

  def destroy
    @expert.destroy
    flash[:success] = 'Удалено'
    redirect_to :action => :index
  end

protected

  def build_expert
    @expert = Expert.new(expert_params)
  end

  def build_meta_tag
    @expert.build_meta_tag if @expert.meta_tag.nil?
  end

  def load_expert
    @expert = Expert.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:danger] = 'не найдено'
    redirect_to :action => :index
  end

  def expert_params
    params.fetch(:expert, {}).permit(:name, :category, :description, :avatar, :gender, meta_tag_attributes: [:meta_title, :meta_keywords, :meta_description])
  end
end

app/controllers/experts_controller.rb
class ExpertsController < ApplicationController
  def index
    @experts = Expert.all
  end

  def show
    @expert = Expert.find(params[:id])
  end
end

app/helpers/experts_helper.rb
module ExpertsHelper
  def expert_image(expert, size)  
    return image_tag(expert.avatar.url(size)) if expert.avatar.exists?
    
    if expert.gender == "m"
      size == :lg ? image_tag("big_man.png") : image_tag("man.png")
    else
      size == :lg ? image_tag("big_woman.png") : image_tag("woman.png")
    end
  end
end

app/views/admin/experts/_form.html.slim
= form.text_field :name, label: "Имя"
= form.text_field :category, label: "Категория"
= form.text_area :description, label: "Описание", class: "wysiwyg"

div.form-group style="margin: 0 160px"
  = image_tag @expert.avatar.url(:thumb) if @expert.avatar.exists?

= form.file_field :avatar, label: "Изображение"

div.form-group style="margin: 0 160px" 
  - Expert::GENDERS.each do |gender|
    = form.radio_button "gender", gender, label: t(gender)


= form.fields_for :meta_tag do |tag|
  = tag.text_field :meta_title
  = tag.text_field :meta_keywords
  = tag.text_field :meta_description

= form.form_group :class => 'form-actions' do
  = form.submit "Сохранить", :class => 'btn btn-primary'

app/views/admin/experts/edit.html.haml
.page-header
  %h2 Изменение специалиста

= comfy_form_for [:admin, @expert] do |form|
  = render form

app/views/admin/experts/index.html.haml
.page-header
  = link_to 'Новый специалист', new_admin_expert_path, :class => 'btn btn-default pull-right'
  %h2= 'Специалисты'

= paginate @experts, :theme => 'comfy'

%table.table.table-hover.table-bordered
  %thead
    %tr
      %th Фото
      %th Имя
      %th Категория
      %th
  %tbody.sortable_table
    - @experts.each do |expert|
      %tr{id: dom_id(expert)}
        %td= expert_image(expert, :medium)
        %td= expert.name
        %td= truncate expert.category
        %td
          .btn-group.btn-group-sm
            = link_to 'Изменить', edit_admin_expert_path(expert), :class => 'btn btn-default'
            = link_to 'Удалить', admin_expert_path(expert), :method => :delete, :data => { :confirm => 'Вы уверены?' }, :class => 'btn btn-danger'

= paginate @experts, :theme => 'comfy'

app/views/admin/experts/new.html.haml
.page-header
  %h2 Новый специалист

= comfy_form_for [:admin, @expert] do |form|
  = render form

app/views/admin/experts/show.html.haml
.page-header
  %h2 Expert
  
= debug @expert